Feature/8 filter by application state
keyko-io/filplus-registry pull request #10
Opened 2023-08-03 14:00 UTC by clriesco

- Added state to card info
- Added filter by state

2023-08-03 14:35 UTC, clriesco commented
#7 
#8

2023-08-04 06:57 UTC, jbesraa requested changes
looks good! added a couple of comments

2023-08-04 06:57 UTC, jbesraa commented on src/app/page.tsx
> +  console.log({ results })
remove log please

2023-08-04 06:57 UTC, jbesraa commented on src/app/page.tsx
> +    keys: [
I would get the keys from one object and put them here, for example: `Object.keys(data[0])`
you need to make sure data[0] is exist though

2023-08-04 06:57 UTC, jbesraa commented on src/app/page.tsx
> +    keys: [
I dont see also where fuse is being triggered. 
maybe add `useEffect` that only runs when `searchTerm` is changed. also when you do search/filter you need to take into account the other parameter, ie:
when there is search, u need to also if any filters are set and when a filter is changed u need to also check if there is a search term

2023-08-04 06:57 UTC, jbesraa commented on src/app/page.tsx
> +            {searchResults?.map((app) => (
Lets add type to `app` here

2023-08-07 07:21 UTC, jbesraa commented on src/app/page.tsx
> +import { Application } from '@/type'
@clriesco where is this defined?

2023-08-07 07:22 UTC, jbesraa commented on src/app/page.tsx
> +import { Application } from '@/type'
the `Application` type

2023-08-07 12:09 UTC, jbesraa approved these changes

2023-08-07 12:10 UTC, merged